name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  post-event:
    runs-on: ubuntu-latest
    steps:
    - name: echo commit message
      run: echo "${GITHUB_SHA:0:7} - ${{ github.event.head_commit.message }}"



